[package]
name = "schema"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
metadata = { version = "0.1.0", path = "../metadata" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
schemars = "1.0.4"
